<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'example\\capacity' => '/Capacity.php',
                'example\\capacitylessthenzeroexception' => '/exceptions/CapacityLessThenZeroException.php',
                'example\\container' => '/Container.php',
                'example\\containerid' => '/ContainerId.php',
                'example\\exception' => '/exceptions/Exception.php',
                'example\\invalidcontaineridexception' => '/exceptions/InvalidContainerIdException.php',
                'example\\invalidnameexception' => '/exceptions/InvalidNameException.php',
                'example\\name' => '/Name.php',
                'example\\port' => '/Port.php',
                'example\\ship' => '/Ship.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
